spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/microservice_user
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://eureka:10086/eureka
